name: Quickstart CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install Foundry CLI
        run: |
          brew tap crowdstrike/foundry-cli
          brew install crowdstrike/foundry-cli/foundry
      - name: Create profile for Foundry CLI
        run: |
          mkdir -p ~/.config/foundry
          rm -f ~/.config/foundry/configuration.yml
          touch ~/.config/foundry/configuration.yml
          echo "profiles:" > ~/.config/foundry/configuration.yml
          echo "- name: Test CID" >> ~/.config/foundry/configuration.yml
          echo "  cloud_region: us-1" >> ~/.config/foundry/configuration.yml
          echo "  credentials:" >> ~/.config/foundry/configuration.yml
          echo "    cid: ${{ secrets.CID }}" >> ~/.config/foundry/configuration.yml
          echo "    api_client_id: ${{ secrets.CLIENT_ID }}" >> ~/.config/foundry/configuration.yml
          echo "    api_client_secret: ${{ secrets.CLIENT_SECRET }}" >> ~/.config/foundry/configuration.yml
          echo "active_profile: Test CID" >> ~/.config/foundry/configuration.yml
          echo "logging.debug: true" >> ~/.config/foundry/configuration.yml
      - name: Install yq
        run: brew install yq
      - name: Remove ids from manifest
        run: |
          yq -i 'del(.. | select(has("id")).id) | del(.. | select(has("app_id")).app_id)' manifest.yml
      - name: Deploy app to Falcon
        run: foundry apps deploy --change-type=major --change-log="e2e deploy"
