name: Quickstart CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-and-release:
    runs-on: ubuntu-latest
    env:
      FOUNDRY_API_CLIENT_ID: ${{ secrets.FOUNDRY_API_CLIENT_ID }}
      FOUNDRY_API_CLIENT_SECRET: ${{ secrets.FOUNDRY_API_CLIENT_SECRET }}
      FOUNDRY_CID: ${{ secrets.FOUNDRY_CID }}
      FOUNDRY_CLOUD_REGION: ${{ secrets.FOUNDRY_CLOUD_REGION }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install required tools
        run: |
          brew tap crowdstrike/foundry-cli
          brew install crowdstrike/foundry-cli/foundry yq
      - name: Prepare app manifest
        run: |
          # Remove IDs from manifest
          yq -i 'del(.. | select(has("id")).id) | del(.. | select(has("app_id")).app_id)' manifest.yml
          
          # Generate unique app name
          yq -i '.name = .name + "-${{ github.actor }}-" + "'$(date +"%Y%m%d%H%M")'"' manifest.yml
          
          echo "Prepared manifest with app name: $(yq '.name' manifest.yml)"
      - name: Deploy app to Falcon
        run: foundry apps deploy --change-type=major --change-log="e2e deploy"
      - name: Release app to Falcon
        run: |
          until foundry apps list-deployments | grep -i "successful"; do
            sleep 1
          done
          echo "Releasing app..."
          foundry apps release --change-type=major --notes="e2e release"
      - name: Delete app from Falcon
        if: always()
        run: |
          foundry apps delete -f
          echo "App deleted successfully"
